
title: &author Jiří Maňák
email: &email manak@z-bionics.com
description: &description Firmware developer, Maker, Co-founder of Z-Bionics, BSc student at FEL CTU in Prague.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://manakjiri.cz" # the base hostname & protocol for your site, e.g. http://example.com
username: &username manakjiri
twitter_username: &twitter_username manakjiri
github_username:  &github_username manakjiri
linkedin_username: &linkedin_username manakjiri

include:
  - _pages

defaults:
  # Projects
  - scope:
      path: "_posts/projects"
      type: posts
    values:
      permalink: project/:title:output_ext
      category: projects

# Build settings
theme: klise
sass:
  style: compressed

# Theme specific.
author:
  name: *author
  bio: *description
  avatar: /assets/content/images/avatar.jpeg
  email: *email
  username: *username
  github: *github_username
  twitter: *twitter_username

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - .gitignore
  - .github
  - Gemfile
  - Gemfile.lock
  - README.md
