# Site settings
title: &author Jiří Maňák
email: &email manak@z-bionics.com
description: &description Firmware developer, Maker, Co-founder of <a href="https://www.z-bionics.com/" target="_blank" rel="noopener">Z-Bionics</a>, BSc student at <a href="https://kyr.fel.cvut.cz/" target="_blank" rel="noopener">FEL CTU</a> in Prague.
image: # This image used for Open Graph more info https://ogp.me/
lang: en-US # default lang
timezone: Europe/Prague # set your timezone
repo: https://github.com/manakjiri/personal-website
username: &username manakjiri
twitter_username: &twitter_username manakjiri
github_username:  &github_username manakjiri
linkedin_username: &linkedin_username manakjiri

# URL settings
url: "https://manakjiri.cz" # the base hostname & protocol for your site
baseurl: # the subpath of your site, e.g. /blog
google_analytics: # leave it blank if not used
fb_appid:


defaults:
  # Projects
  - scope:
      path: "_posts/projects"
      type: posts
    values:
      permalink: project/:title/
      category: projects


# Build settings
theme: klise
number_of_posts: 3 # Homepage limit posts
sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles

# Theme specific.
author:
  title: *author
  name: *author
  bio: *description
  avatar: /assets/content/images/avatar.jpeg
  email: *email
  username: *username
  github: *github_username
  twitter: *twitter_username


include:
  - _pages
  - .htaccess

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - .gitignore
  - .github
  - Gemfile
  - Gemfile.lock
  - README.md
