# Site settings
title: &author Jiří Maňák
tagline: Personal Portfolio and Blog
description: &description Maker of things who strives to take part in creating great products.
image: https://assets.manakjiri.cz/ogp.png # This image is used for Open Graph more info https://ogp.me/
lang: en-US # default lang
timezone: Europe/Prague # set your timezone
repo: https://github.com/manakjiri/personal-website
email: &email manak@z-bionics.com
username: &username manakjiri
twitter_username: &twitter_username manakjiri
github_username:  &github_username manakjiri
linkedin_username: &linkedin_username manakjiri

# URL settings
url: "https://manakjiri.cz" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog
google_analytics: # leave it blank if not used
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

defaults:
  # Projects
  - scope:
      path: "_posts/projects"
      type: posts
    values:
      permalink: "project/:title/"
      category: projects

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Build settings
number_of_posts: 3 # Homepage limit posts
sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles

# Theme specific.
author:
  title: *author
  name: *author
  bio: *description
  avatar: https://assets.manakjiri.cz/avatar.jpeg
  email: *email
  username: *username
  github: *github_username
  twitter: *twitter_username

include:
  - _pages
  - .htaccess

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - .gitignore
  - .github
  - Gemfile
  - Gemfile.lock
  - README.md
