name: Build and deploy to manakjiri.cz

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Build with Jekyll
        # Outputs to the './_site' directory by default
        run: bundle exec jekyll build --trace --future --verbose
        env:
          JEKYLL_ENV: production

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: _site/
          name: webroot
          retention-days: 3
          overwrite: true

  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: webroot
          path: webroot

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy webroot --project-name=manakjiri-website --commit-dirty=true
