name: Build and deploy to manakjiri.cz

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:

    runs-on: ['self-hosted', 'docker']

    steps:
      - uses: actions/checkout@v4

      - name: Setup Jekyll
        run: |
          rbenv install --skip-existing
          gem install bundler
          bundle install

      - name: Mount Assets
        run: |
          mkdir -p ./assets/content
          mount ./assets/content
      
      - name: Build Site
        run: bundle exec jekyll build --trace --future --verbose
      
      - name: Check for missing assets
        run: |
          if [ -f _site/missing_assets.txt ]; then
            echo "Missing assets:"
            cat _site/missing_assets.txt
            exit 1
          fi

      - name: Deploy Site
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_dir: "./_site"
          remote_dir: "."
          delete: false

      - name: Unmount Assets
        if: always()
        run: umount ./assets/content