name: Build and deploy to manakjiri.cz

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:

    runs-on: ['self-hosted', 'docker']

    steps:
      - uses: actions/checkout@v3

      - name: Setup Jekyll
        run: |
          gem install bundler
          bundle install

      - name: Build Site
        run: bundle exec jekyll build --trace
      
      - name: Deploy Site
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_dir: "./_site"
          remote_dir: "."
          delete: true

      - name: Link Assets
        run: ln -s /mnt/website_assets ./website_assets || exit 0
      
      - name: Deploy Assets
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_dir: "./website_assets"
          remote_dir: "assets"
